### ISSUE TITLE
ImportError: No module named _caffe

### ISSUE THREAD

**Issue by DRAhmadFaraz** [alexgkendall/caffe-posenet#29]
@alexgkendall 

in directory "**/home/ahmad/Desktop/caffe-posenet/posenet/scripts**"
I type "**python create_posenet_lmdb_dataset.py**"

with Change lines 1, 11 & 12 to the appropriate directories

i got this error.

Regards

_Traceback (most recent call last):
  File "create_posenet_lmdb_dataset.py", line 7, in <module>
    import caffe
  File "/home/ahmad/Desktop/caffe-posenet/python/caffe/__init__.py", line 1, in <module>
    from .pycaffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, RMSPropSolver, AdaDeltaSolver, AdamSolver
  File "/home/ahmad/Desktop/caffe-posenet/python/caffe/pycaffe.py", line 13, in <module>
    from ._caffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, \
ImportError: No module named _caffe_

![screenshot from 2019-01-07 08-07-43](https://user-images.githubusercontent.com/38114191/50756213-5938f000-1253-11e9-8266-1a760f4ac72c.png)

**Comment by DRAhmadFaraz** [comment]
@alexgkendall
